# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 01:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinyread', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyReadArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u4fe1\u606f',
                'verbose_name_plural': '\u8bc4\u8bba\u4fe1\u606f',
            },
        ),
        migrations.AlterField(
            model_name='tinyreadarticle',
            name='content',
            field=models.CharField(max_length=200, verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='tinyreadarticlecomment',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyread.TinyReadArticle', verbose_name='\u8bc4\u8bba\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='tinyreadarticlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4eba'),
        ),
    ]
