# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 15:46
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('title_image', models.ImageField(default='static/images/article_head/default.png', upload_to='static/images/article_head/%Y/%m', verbose_name='\u9884\u89c8\u56fe\u7247')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('favorite_num', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570\u91cf')),
                ('comment_num', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('url', models.URLField(default='http://127.0.0.1:8000/1/1.html', verbose_name='\u6587\u7ae0\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u8be6\u60c5',
                'verbose_name_plural': '\u6587\u7ae0\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u6d4b\u8bd5\u6587\u7ae0',
                'verbose_name_plural': '\u6d4b\u8bd5\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('count', models.IntegerField(default=0, verbose_name='\u6587\u7ae0\u6570\u91cf')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0\u7c7b\u578b',
                'verbose_name_plural': '\u6587\u7ae0\u7c7b\u578b',
            },
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType', verbose_name='\u6240\u5c5e\u6587\u7ae0\u7c7b\u578b'),
        ),
    ]
