# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='new_or_update',
            field=models.CharField(choices=[('new', '\u65b0\u5efa'), ('update', '\u4fee\u6539')], default='new', max_length=6, verbose_name='\u7f16\u8f91\u7c7b\u578b'),
        ),
    ]
