# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHoleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='\u6811\u6d1e\u5185\u5bb9')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('fav_count', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570\u91cf')),
                ('comment_count', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u6570\u91cf')),
                ('address', models.CharField(max_length=100, verbose_name='\u53d1\u5e03\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u6811\u6d1e\u5185\u5bb9',
                'verbose_name_plural': '\u6811\u6d1e\u5185\u5bb9',
            },
        ),
    ]
