# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 14:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treehole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHoleArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('comment_content', models.CharField(default='\u8bc4\u8bba', max_length=200, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u4fe1\u606f',
                'verbose_name_plural': '\u8bc4\u8bba\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='treeholearticle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4eba'),
        ),
        migrations.AddField(
            model_name='treeholearticlecomment',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treehole.TreeHoleArticle', verbose_name='\u8bc4\u8bba\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='treeholearticlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4eba'),
        ),
    ]
